name: Run tests

on:
  push:

jobs:
  tests:
    name: Run the tests
    strategy:
      matrix:
        os: 
          - macos-10.15
          - macos-11
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          brew uninstall --force bats
          brew install bats-core

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_KEY }}

      - name: Run tests
        run: |
          make test
