name: Run tests

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  tests:
    name: Run the tests
    strategy:
      matrix:
        os: 
          - macos-10.15
          - macos-11
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          brew uninstall --force bats
          brew install bats-core

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_KEY }}

      - name: Add tmate API key
        env:
          TMATE_API_KEY: ${{ secrets.TMATE_API_KEY }}
        run: |
          echo "set tmate-api-key '$TMATE_API_KEY'" > ~/.tmate.conf

      - name: Setup tmate debugging session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Run tests
        run: |
          make test
